### ISSUE TITLE
Exit on encoding error

### ISSUE THREAD

**Issue by ziorufus** [SIMPATICOProject/SimpaticoTAEServer#4]
I got this error with the UK demo:

```
Traceback (most recent call last):
  File "Run_TCP_Syntactic_Simplifier_Server.py", line 87, in <module>
    print "Sending " + str(ss_output) + " To User"
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 72: ordinal not in range(128)
```

The program then exited.
Is it possible to catch these errors and eventually return a null result (or the input text, untouched), instead of exiting?

**Comment by ziorufus** [comment]
I noticed that the error is on the `print` command, therefore I've restarted the server after commenting the line. We'll see if it works.

**Comment by carolscarton** [comment]
Did it work?

**Comment by ziorufus** [comment]
Nope :(

```
Traceback (most recent call last):
  File "Run_TCP_Syntactic_Simplifier_Server.py", line 88, in <module>
    conn.send(ss_output)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 72: ordinal not in range(128)
```

**Comment by carolscarton** [comment]
Can you send the sentences that you are trying to simplify?

**Comment by ziorufus** [comment]
It's a sentence from Sheffield pilot. I think it's the `’` in `Majesty’s`.

```
Sentance Received : Publishing all UK legislation is a core part of the remit of Her Majesty’s Stationery Office (HMSO), part of The National Archives, and the Office of the Queen's Printer for Scotland.
Language :en
Traceback (most recent call last):
  File "Run_TCP_Syntactic_Simplifier_Server.py", line 88, in <module>
    conn.send(ss_output)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 72: ordinal not in range(128)
```

**Comment by carolscarton** [comment]
Are you using the code in the main branch or in the demo branch?

**Comment by ziorufus** [comment]
Master

**Comment by carolscarton** [comment]
Okay. I have solved the issue for English (although IT and ES may have similar problems as well). 

I have updated both the Master and the Demo branches. However, where are you trying to use the SS? Is it for the demo? If so, you should use the Demo branch since it has the complexity checker and confidence model and also has support for the three languages (which is not in the master).

**Comment by ziorufus** [comment]
Hi! Everything seems work.
I had to replace `from nltk.tokenize import StanfordTokenizer` with `from nltk.tokenize import stanford` (probably due to a different version of NLTK).

I also disabled Italian and Galician simplifiers (they are not needed for the SAT).

**Comment by ziorufus** [comment]
The bug is back :(

```
Traceback (most recent call last):
  File "Run_TCP_Syntactic_Simplifier_Server.py", line 108, in <module>
    conn.send(ss_output)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 72: ordinal not in range(128)
```

**Comment by carolscarton** [comment]
Which is the sentence now?

**Comment by ziorufus** [comment]
The same :(

```
Sentance Received : Publishing all UK legislation is a core part of the remit of Her Majesty’s Stationery Office (HMSO), part of The National Archives, and the Office of the Queen's Printer for Scotland.
```

I checked the branch and the code, and everything seems correct.
```
$ git pull
Already up-to-date.
$ git status
On branch ijcnlp2017-demo
Your branch is up-to-date with 'origin/ijcnlp2017-demo'.
```

**Comment by carolscarton** [comment]
I think there was something missing in the code. Just updated it now. Can you please pull it from the server and try again?

**Comment by ziorufus** [comment]
It seems ok now. Thank you!

**Comment by ziorufus** [comment]
I tested a sentence on Spanish, it gives me some warning, but the simplification is performed correctly.

The sentence is: Juan Carlos I, rey de España, presidirá el acto de homenaje a Cervantes.
Simplification: Juan Carlos I presidirá el acto de homenaje a Cervantes . Juan Carlos I es rey de España .

This is the warning in the log:
```
Sentance Received : Juan Carlos I, rey de España, presidirá el acto de homenaje a Cervantes.
Language :es
simpatico_ss/simpatico_ss_es/simplify.py:681: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if sent_tok[1].lower() in ("qué", "dónde", "cuándo", "quiénes", "quién", "cuál", "cuáles", "cómo", "cuánto", "cuánta", "cuántos", "cuántas") and sent_tok[-1] == "?":
simpatico_ss/simpatico_ss_es/simplify.py:645: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if sent == ant:
simpatico_ss/simpatico_ss_es/analysis.py:22: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if any([s.lower() in self.cc for s in self.sentence]):
```
